#!/bin/sh

set -e

case $1 in
    configure)
        if [ -f "/opt/MegaRAID/MegaCli/MegaCli64" ]; then 
            ln -s /opt/MegaRAID/MegaCli/MegaCli64 /usr/sbin/MegaCli
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
